services:
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: fvst
      POSTGRES_PASSWORD: fvst
      POSTGRES_DB: fvst
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - paritet_network

  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - paritet_network

  mongo:
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - paritet_network

volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  paritet_network:
    driver: bridge
