FROM nginx:latest
# RUN rm /etc/nginx/conf.d/default.conf # Можно оставить, если это не вызывает проблем, или удалить, если вызывает ошибку
COPY tooling/configs/nginx/nginx.conf /etc/nginx/nginx.conf
COPY tooling/configs/nginx/dev.d/dev.conf /etc/nginx/nginx.conf 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]